
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: bazar
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: