spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bazar
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
bot:
  token: 8210506213:AAGnyhKEkKFk-K_6kegIUFRgwalSu6tp47Y